Inc12
fortuna91/go_ya_praktikum pull request #11
Opened 2022-04-28 10:25 UTC by fortuna91

2022-05-01 11:21 UTC, Bazys requested changes
Необходимо переделать работу с БД.
Нужна структура в которой будет хранится connection к БД
описать интрефейс и реализовать его для этой структуры

2022-05-01 11:21 UTC, Bazys commented on cmd/server/main.go
> +		if len(config.DB) > 0 {
а просто с пустой строкой сравнить?
либо хранить по ссылке и сравнивать с nil

2022-05-01 11:21 UTC, Bazys commented on internal/db/db.go
> +	dbConn := connect(dbAddress)
каждый раз создавать для пинга новое соединение очень дорого.
лучше если в качестве параметра передать в функцию само соединение.

2022-05-02 14:53 UTC, fortuna91 commented on cmd/server/main.go
> +		if len(config.DB) > 0 {
я прочитала, что такая проверка и проверка на пустую строку в Го равнозначна . И то и другое используется во внутренних любах

2022-05-10 07:33 UTC, merged