Inc3
fortuna91/go_ya_praktikum pull request #2
Opened 2022-03-29 11:41 UTC by fortuna91

2022-03-29 15:21 UTC, Bazys requested changes
Предлагаю все таки вынести логикиу из пакета main

2022-03-29 16:31 UTC, fortuna91 commented
> Предлагаю все таки вынести логикиу из пакета main

из агента только? В сервере вроде +- не осталось. Или чтобы вообще  мене остался условный run()? Все в internal  переносим, как понимаю?

2022-03-30 11:30 UTC, Bazys requested changes
graceful shutdown реализовать до конца

2022-03-30 11:30 UTC, Bazys commented on internal/agent/main.go
> +package agent
название файла всегда будет вводить в заблуждение.
Лучше переименовать

2022-03-30 11:30 UTC, Bazys commented on cmd/server/main.go
> +			os.Exit(0)
в данном случае ничем не отличается от простой остановки приложения

2022-03-30 11:30 UTC, Bazys commented on cmd/server/main.go
> +	r := run.NewRouter()
посмотри как реализовано вот тут
https://github.com/go-chi/chi/blob/master/_examples/graceful/main.go

2022-03-30 11:30 UTC, Bazys commented on internal/agent/main.go
> +		time.Sleep(time.Second * 2)
можно использовать time.Ticker
https://gobyexample.com/tickers

2022-03-30 11:30 UTC, Bazys commented on internal/handlers/handlers.go
> +	var form = `<html>
Это не обязательно!
Почитай про https://pkg.go.dev/html/template

2022-03-30 11:30 UTC, Bazys commented on internal/metrics/metrics.go
> +	lock   sync.RWMutex
если не указывать имя, а просто "наследовать" то не нужны будут длинные вызовы типа metrics.lock.Lock()

2022-03-30 11:54 UTC, fortuna91 commented on internal/agent/main.go
> +package agent
упс, забыла

2022-04-01 07:56 UTC, Bazys approved these changes
отлично!

2022-04-01 07:56 UTC, Bazys commented on cmd/agent/main.go
> +	go func() {
а тут не стала исправлять?

2022-04-01 07:56 UTC, Bazys commented on internal/agent/agent.go
> +	ticker := time.NewTicker(2 * time.Second)
сейчас не страшно, но на будущее - константу лучше не использовать - заводи переменную для этих целей.
В дальнейшем сможешь через конфиг это настраивать.

2022-04-01 07:56 UTC, Bazys commented on internal/handlers/handlers.go
> +// fixme maybe for feature it has to be channel with mutex
каналы и горутины будете изучать в 4 спринте

2022-04-01 07:56 UTC, Bazys commented on internal/handlers/handlers.go
> +	const tmplHTML = `<!DOCTYPE html>
супер!

2022-04-01 16:20 UTC, fortuna91 commented on cmd/agent/main.go
> +	go func() {
ну тут нет сервера. Я думала смысл в том, чтобы корректно потушить сервер. А тут просто надо завершить работу... Или я не до конца поняла

2022-04-01 16:22 UTC, merged